// This file is "main.dart"
import '../../data/models/tier.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

import 'asset.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'account.freezed.dart';
// optional: Since our Account class is serializable, we must add this line.
// But if Account was not serializable, we could skip it.
part 'account.g.dart';

@freezed
class Account with _$Account {
  @JsonSerializable(explicitToJson: true)
  const factory Account(
      {required int id,
      required int userID,
      required int walletid,
      // required Tier tierID,
      // required Asset assetID,
      String? accountname,
      double? total,
      double? available,
      double? inorder,
      double? btcvalue,
      double? createdAt,
      double? updatedAt}) = _Account;

  factory Account.fromJson(Map<String, Object?> json) =>
      _$AccountFromJson(json);
}



// class ColorSerialiser implements JsonConverter<Tier, int> {
//   const ColorSerialiser();

//   @override
//   Tier fromJson(int json) => Tier(json);

//   @override
//   String? toJson(Tier tier) => tier.name;
// }