// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

import '../enums/transactionstatus.dart';
import 'asset.dart';
import 'network.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'addresss.freezed.dart';
// optional: Since our Addresss class is serializable, we must add this line.
// But if Addresss was not serializable, we could skip it.
part 'addresss.g.dart';

@freezed
class Addresss with _$Addresss {
  // @JsonSerializable(explicitToJson: true)

  const factory Addresss(
      {
            required int  id,
// required   Asset assetID,
// required  Network NetworkID,
      String? addresssname,
      String? label,
      String? asset,
      String? note,
      bool? whitelist,
      String? addresss,
        //  TransactionStatus? transactionStatusId,
      double? createdAt,
      double? updatedAt
       }) = _Addresss;

  factory Addresss.fromJson(Map<String, Object?> json) =>
      _$AddresssFromJson(json);
}
