// // This file is "main.dart"
// import 'package:freezed_annotation/freezed_annotation.dart';
// import 'package:flutter/foundation.dart';

// import '../enums/transactionstatus.dart';
// import 'account.dart';
// import 'addresss.dart';

// // required: associates our `main.dart` with the code generated by Freezed
// part 'asset.freezed.dart';
// // optional: Since our Asset class is serializable, we must add this line.
// // But if Asset was not serializable, we could skip it.
// part 'asset.g.dart';

// @freezed
// class Asset with _$Asset {  
//   @JsonSerializable(explicitToJson: true)

//   const factory Asset( 
//       {
//             required int  id,

//     //  required Account accountID,
//         //  required Addresss addressID, 
//      String?    tokenId,
//   String? nftContract,
// int? nitialSupply,
//   String?image,
// String? tokenURI,
//        String? name,
//       String? typeoff,
//       String? uri,
//       double? createdAt,
//       double? updatedAt,
//       // TransactionStatus? transactionStatusId
//       }) = _Asset;

//   factory Asset.fromJson(Map<String, Object?> json) => _$AssetFromJson(json);
// }
