// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'category.freezed.dart';
// optional: Since our Category class is serializable, we must add this line.
// But if Category was not serializable, we could skip it.
part 'category.g.dart';

@freezed
class Categoryx with _$Categoryx {
  const factory Categoryx({
    required int id,
    required String name,
    required String desc,
    required String slug
  }) = _Categoryx;

  factory Categoryx.fromJson(Map<String, Object?> json)
      => _$CategoryxFromJson(json);
}