// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'coin.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'coin.g.dart';

@freezed
class Coin with _$Coin {
  
  const factory Coin(
      {   
         required int  id,
      String? symbol,
      String? name,
      String? image,
      double? current_price,
      double? market_cap,
      double? market_cap_rank,
      double? fully_diluted_valuation,
      double? total_volume,
      double? high_24h,
      double? low_24h,
      double? price_change_24h,
      double? price_change_percentage_24h,
      double? market_cap_change_24h,
      double? market_cap_change_percentage_24h,
      String? circulating_supply,
      double? total_supply,
      double? max_supply,
      double? ath,
      double? ath_change_percentage,
      String? ath_date,
      double? atl,
      double? atl_change_percentage,
      String? tl_date,
      double? roi,
      String? last_updated}) = _Coin;

  factory Coin.fromJson(Map<String, Object?> json) => _$CoinFromJson(json);
}
