// This file is "main.dart"
import '../../data/models/category.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'collection.freezed.dart';
// optional: Since our Collection class is serializable, we must add this line.
// But if Collection was not serializable, we could skip it.
part 'collection.g.dart';

@freezed
class Collection with _$Collection {
  const factory Collection({
    required int id,
    required String title,
    required String description,
    required String banner,
    required String name,
    required String properties1,
    required String properties2,
    required String links1,
    required String links2,
    required String links3,
    // required Categoryx  category,
  }) = _Collection;

  factory Collection.fromJson(Map<String, Object?> json) =>
      _$CollectionFromJson(json);
}
