// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'fee.freezed.dart';
// optional: Since our Fee class is serializable, we must add this line.
// But if Fee was not serializable, we could skip it.
part 'fee.g.dart';

@freezed
class Fee with _$Fee {
  const factory Fee({
    required int  id,
    String? fiatcryptotype,
    String? cryptofiatpairs,
    String? name,
    String? feetype,
    String? feerate,
    double? createdAt,
    double? updatedAt

  }) = _Fee;

  factory Fee.fromJson(Map<String, Object?> json)
      => _$FeeFromJson(json);
}