// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'kyc.freezed.dart';
// optional: Since our Kyc class is serializable, we must add this line.
// But if Kyc was not serializable, we could skip it.
part 'kyc.g.dart';

@freezed
class Kyc with _$Kyc {
  const factory Kyc({
        required int  id,

    required String name,
    required String desc,
    required String slug,
   required String   externaluserid,
 required String  applicantId,
 required String  inspectionId,
 required String  correlationId,
 required String  type,
 required String  reviewResult,
 required String  reviewStatus,
 required String createdAt,
 required String  clientId
  }) = _Kyc;

  factory Kyc.fromJson(Map<String, Object?> json)
      => _$KycFromJson(json);
}