// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

import '../enums/transactionstatus.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'limit.freezed.dart';
// optional: Since our Limit class is serializable, we must add this line.
// But if Limit was not serializable, we could skip it.
part 'limit.g.dart';

@freezed
class Limit with _$Limit {
  const factory Limit({
       required int  id,

 String? fiattradingpair,
    String? typeoff,
    String? asset,
    String? slug,
    double? dailyconfirmationlimit,
    double? dailyapprovallimit,
    double? weeklyapprovallimit,
    double? weeklyconfirmation,
      double? onetimeap,
    double? onetimeapprovallimit,
    double? onetimeconfirmationlimit,
    double? pertransactionminlimit,
    double? pertransactionmaxlimit,
    double? hrs24userxchnagelimit,
    double? hrs24platformxchangelimit,
     double? createdAt,
    double? updatedAt,
      //  required TransactionStatus transactionStatusId

  }) = _Limit;

  factory Limit.fromJson(Map<String, Object?> json)
      => _$LimitFromJson(json);
}