// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

import '../enums/transactionstatus.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'network.freezed.dart';
// optional: Since our Network class is serializable, we must add this line.
// But if Network was not serializable, we could skip it.
part 'network.g.dart';

@freezed
class Network with _$Network {
  const factory Network({
    required String  name,
    required int  id,
  double? createdAt,
    double? updatedAt,
      // required TransactionStatus transactionStatusId

  }) = _Network;

  factory Network.fromJson(Map<String , Object?> json)
      => _$NetworkFromJson(json);
}