// // This file is "main.dart"
// import 'package:cx/data/models/transaction.dart';
// import 'package:cx/presentation/pro/add_payment_method.dart';
// import 'package:freezed_annotation/freezed_annotation.dart';
// import 'package:flutter/foundation.dart';

// import '../enums/transactionstatus.dart';

// // required: associates our `main.dart` with the code generated by Freezed
// part 'order.freezed.dart';
// // optional: Since our Order class is serializable, we must add this line.
// // But if Order was not serializable, we could skip it.
// part 'order.g.dart';

// @freezed
// class Order with _$Order {
//   @JsonSerializable(explicitToJson: true)

//   const factory Order({
//     required int  id,
// // required  PaymentMethod paymentID,
// // required  Transaction transactionID,
//     double? datetime,
//     String?  pairs,
//     String?  orderType,
//     String?  direction,
//     double? orderPrice,
//     double? unfilledQty,
//     double? orderTime,
//     double? total,
//     double? orderValueAvg,
//     double? averagePrice,
//     double? executed,
//     double? filledValue,
//     double? filledPrice,
//     double? filledQty,
//     double? tradingFee,
//     double? filledTime,
//         double? createdAt,

//   }) = _Order;

//   factory Order.fromJson(Map<String , Object?> json)
//       => _$OrderFromJson(json);
// }