// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'paymentmethod.freezed.dart';
// optional: Since our Paymentmethod class is serializable, we must add this line.
// But if Paymentmethod was not serializable, we could skip it.
part 'paymentmethod.g.dart';

@freezed
class Paymentmethod with _$Paymentmethod {
  const factory Paymentmethod({
    required String name,
    required int  id,
    String? fullname,
    int? bankcardno,
    double? expirydate,
    int? cvc,
    String? bankbranch,
    int? bankaccount,
    String? bankname,
    String? addresss,
    String? iban,
    String? city,
    String? state,
    String? country,
    String? postcode,
    int? createdAt,
    int? updatedAt
  }) = _Paymentmethod;

  factory Paymentmethod.fromJson(Map<String, Object?> json)
      => _$PaymentmethodFromJson(json);
}