// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'permission.freezed.dart';
// optional: Since our Permission class is serializable, we must add this line.
// But if Permission was not serializable, we could skip it.
part 'permission.g.dart';

@freezed
class Permission with _$Permission {
  const factory Permission({
        required int  id,

    required String name,
    required String desc,
    required String slug
  }) = _Permission;

  factory Permission.fromJson(Map<String, Object?> json)
      => _$PermissionFromJson(json);
}