// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'role.freezed.dart';
// optional: Since our Role class is serializable, we must add this line.
// But if Role was not serializable, we could skip it.
part 'role.g.dart';

@freezed
class Role with _$Role {
  const factory Role({
        required int  id,
    required String name,
    required String desc,
    required String slug
  }) = _Role;

  factory Role.fromJson(Map<String, Object?> json)
      => _$RoleFromJson(json);
}