// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'setting.freezed.dart';
// optional: Since our Setting class is serializable, we must add this line.
// But if Setting was not serializable, we could skip it.
part 'setting.g.dart';

@freezed
class Setting with _$Setting {
  const factory Setting({
        required int  id,
    required String name,
    required String desc,
    required String slug
  }) = _Setting;

  factory Setting.fromJson(Map<String, Object?> json)
      => _$SettingFromJson(json);
}