// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

import 'fee.dart';
import 'limit.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'tier.freezed.dart';
// optional: Since our Tier class is serializable, we must add this line.
// But if Tier was not serializable, we could skip it.
part 'tier.g.dart';

@freezed
class Tier with _$Tier {
  @JsonSerializable(explicitToJson: true)

  const factory Tier(
      {
       required int  id,
// required  Fee feeID,
// required Limit LimitID,
      String? desc,
      String? name,
      String? slug,
      int? level,
      double? createdAt,
      double? updatedAt
      }) = _Tier;

  factory Tier.fromJson(Map<String, Object?> json) => _$TierFromJson(json);
}
