// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

import 'Asset.dart';
import 'account.dart';
import 'order.dart';
import 'p2p.dart';
import 'paymentmethod.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'transaction.freezed.dart';
// optional: Since our Transaction class is serializable, we must add this line.
// But if Transaction was not serializable, we could skip it.
part 'transaction.g.dart';

@freezed
class Transaction with _$Transaction {
  @JsonSerializable(explicitToJson: true)

  const factory Transaction({
 
      required int  id,
//   required  Paymentmethod  paymentID,
//  required  Account accountID,
//  required  Asset assetID,
//  required  Order orderID,
//  required  P2P  p2pID,
    double? listPrice,
    double? offer,
    double? reservePrice,
    double? startPrice,
    double? startDate,
    double? endDate,
    double? reserveBid,                 
    double? scheduledBid,
    double? timeRemainingA,
    double? timeRemainingB,
    double? noOfTimesItemSold,
    double? amount,         
    double? newAmount,         
    double? comission,
    String? seller,
    String? creator,           
    String? buyer,
    double? sellerIncome,
      String? label,
    String? txid,
    String? typeoff,
    String?  sender,
    String?  destination,
      double? royalty,
    double? lastSaleTime,
double? first,
double? last,
double? timeToAuction,
double? DurationA,
double? DurationB,
double? networkFee,
     double? createdAt,
    double? updatedAt,
    
  }) = _Transaction;

  factory Transaction.fromJson(Map<String, Object?> json)
      => _$TransactionFromJson(json);
}