// This file is "main.dart"
import 'dart:convert';

import '../../data/models/paymentmethod.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:jwt_decoder/jwt_decoder.dart';

import 'Order.dart';
import 'addresss.dart';
import 'collection.dart';
import 'kyc.dart';
import 'permission.dart';
import 'role.dart';
import 'setting.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user.freezed.dart';
// optional: Since our User class is serializable, we must add this line.
// But if User was not serializable, we could skip it.
part 'user.g.dart';

@freezed
class User with _$User {
  @JsonSerializable(explicitToJson: true)
  const factory User({
    int? id,
    String? hashed_password,
    String? walletAddress1,
    String? phone,
    String? externaluserid,
    String? applicantId,
    String? inspectionId,
    String? walletInstanceid2,
    String? refereeid,
    String? referalid,
    String? referalcode,
    int? referalcount,
    String? wryeuserid,
    String? stripeid,
    String? email,
    String? jwttoken,
    String? clientid,
    String? clientsecret,
    String? revoked,
    String? refreshToken,
    String? revokedbyip,
    String? replacedbytoken,
    String? profile,
    String? subemail,
    String? subhashed_password,
    String? thashed_password,
    String? reservationid,
    String? links1,
    String? links2,
    String? links3,
    String? nickname,
    String? redirecttolink,
    String? kyclevel,
    bool? iskycverified,
    bool? isfroozen,
    bool? issubaccount,
    String? note,
    String? remarks,
    DateTime? dob,
    String? subusername,
    String? username,
    String? firstname,
    String? lastname,
    int? age,
    String? nationality,
    String? about,
    String? password,
    String? confirmpassword,
    DateTime? updatedAt,
    // Order? orders,
    //   Paymentmethod? paymentmethod,
    //  required Permission permissoins,
    //   Collection? collections,
    //   Addresss? address,
    //   Setting? settings,
    //  required Role roles,
    //   Kyc? kyc,
  }) = _User;

  factory User.fromJson(Map<String, Object?> json) => _$UserFromJson(json);
}
